### ISSUE TITLE
Didn`t work with load balances

### ISSUE THREAD

**Issue by rayout** [joshuakarjala/rancher-lb-sync#1]
Even didn`t start If i use load balancer for "sync".
I need a load balancer because I can not do expose at the service.

``` yml
lb:
  expose:
  - 80:80
  tty: true
  image: rancher/load-balancer-service
  links:
    nginx: nginx
  stdin_open: true
  labels:
    rancher.lb.sync.register: true
    rancher.lb.sync.domain: test1.dev
    rancher.lb.sync.ext_port: 80
    rancher.lb.sync.service_port: 80
nginx:
  image: nginx:1.9
  tty: true
  stdin_open: true
  volumes_from:
    - web
  labels:
    io.rancher.sidekicks: php-fpm, web
web:
  labels:
    io.rancher.container.start_once: true
    io.rancher.container.pull_image: always
  image: tain/test-web1:latest
  volumes:
    - /var/www/test
    - /etc/nginx/conf.d
  entrypoint: /bin/true
php-fpm:
  image: php:5.5-fpm
  tty: true
  stdin_open: true
  volumes_from:
    - web
```
